---
- hosts: two
  become: true
  become_user: root
  tasks:
          - import_tasks: install_webserver.yml
            when: ansible_os_family == "RedHat"
          - import_tasks: install_webserver_debian.yml
            when: ansible_os_family == "Debian" 
