---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars:
          x:
                  - 3
                  - 4
                  - 5
          y: 5
  tasks:
          - name: comparision operators
            debug:
                    msg:
                            - "The list or sequence x is: {{x}} and y value is {{y}}"
                            - "Y is there in x: {{y in x}}"
                            - "10 in x: {{10 in x}}"
                            - "20 not in x: {{20 not in x}}"
                            - "y not in x: {{y not in x}}"
 

