---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars:
          x: 49
  tasks:
          - name: test operators
            debug:
                    msg:
                            
                          - "x is defined {{x is defined}}"
                          - "y is defined {{y is defined}}"
                          - "z is defined {{z is undefined}}"
