---
- hosts: two
  become: true
  become_user: root
  tasks:
          - name: Displaying ansible_facts
            debug:
                    msg:
                            - "The ansible distribution is: {{ansible_distribution}}"
                            - "The os family is: {{ansible_os_family}}" 

