---
- hosts: all
  become: true
  become_user: root
  tasks:
          - name: copy to tmp with idempotent approach
            copy:
                    dest: /tmp/resolv1.conf
                    content: "nameserver 192.168.43.68"
