---
- hosts: one
  become: true
  become_user: root
  vars:
          remote_dir: /etc/ansible/facts.d
          facts_file: custom.fact
  tasks:
          - name: create a remote directory
            file:
                    state: directory
                    path: "{{ remote_dir }}"
                    recurse: yes
          - name: copy a file
            copy:
                    src: "{{ facts_file }}"
                    dest: "{{ remote_dir }}"


