---
- hosts: two
  become: true
  become_user: root
  tasks:
            - name: copy the file
              copy:
                    src: /home/ansible/yum.yml
                    dest: /tmp/
                