---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars:
          x: 56
          y: 27
  tasks:
          - name: Arithmetic operators
            debug:
                    msg:
                            - "The value of x is: {{x}}"
                            - "The value of y is: {{y}}"
                            - "{{x}} + {{y}} = {{x+y}}"
                            - "{{x}} - {{y}} = {{x-y}}"

