---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars:
          x: 25
          my_name: "ansible playbook"
  vars_prompt:
          - name: y
            prompt: Enter the value of y
            private: no
          - name: username
            prompt: Enter the username
            private: no
          - name: password
            prompt: Enter the password
            private: yes
  tasks:
          - name: Displaying the var
            debug:
                    msg:
                            - "The value of x is: {{x}}"
                            - "The value of my_name is: {{my_name}}"
                            - "The value of y is: {{y}}"
                            - "The username is: {{username}} and The password is: {{password}}"


