---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  tasks:
          - block:
                  - name: Finding files in /home/ansible
                    command: "ls /home/ansible/ansible"
                    register: ls_out
            rescue:
                  - debug:
                            msg: "The Given Path /home/ansible/nsible is not a valid path"
            always:
                  - debug:
                            msg: "This will always executes"


