---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  tasks:

          #        command: "ls /home"
          #  register: out
          #  failed_when: out.rc==0
          # - debug: var=out
          - command: "ls /home"
            register: out
          - fail:
                  msg: "failed because rc equal to 0"
            when: out.rc==0

