---
- hosts: localhost
  become: true
  become_user: root
  tasks:
          - name: install nano
            yum:
                    name: nano
                    state: latest
          - name: install httpd
            yum:
                    name: httpd
                    state: latest
