---
- hosts: two
  become: true
  become_user: root
  tasks:
          - name: install multiple packages
            yum:
                    name:
                            - tree
                            - dhcp
                    state: latest

