---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars_prompt:
          - name: x
            prompt: Enter the value of x
            private: no
          - name: y
            prompt: Enter the value of y
            private: no
  tasks:
          - name: Working with arithmetic operators with vars prompt
            debug:
                    msg:
                            - "The value of x is: {{x}}"
                            - "The value of y is: {{y}}"

