---
- hosts: two
  become: true
  become_user: root
  gather_facts: false
  tasks:
          - yum:
                  name: gettext-devel
                  state: present
          - yum:
                  name: perl-CPAN
                  state: present

          - yum:
                  name: perl-devel
                  state: present
          - yum:
                  name: zlib-devel
                  state: present
          - yum:
                  name: openssl-devel
                  state: present



