---
- hosts: localhost
  become: true
  become_user: root
  tasks:
          - import_tasks: install_webserver_RedHat.yml
            when: ansible_distribution == 'RedHat'
          - import_tasks: install_webserver_debian.yml
            when: ansible_distribution == 'Debian'


