---
- hosts: localhost
  become: true
  become_user: root
  tasks:
          - name: including vars from a file
            include_vars: required_variables_for_{{ansible_os_family}}.yml
          - name: displaying variables from a file
            debug:
                    msg:
                            - "pkg_name: {{pkg}}"

