---
- hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  vars:
          x: 5
          y: 67
          my_list: [5,6,7]
  tasks:
          - name: working with conditional statements
            debug:
                    msg:
                            - "The value of x is: {{x}} and y is: {{y}}"
            when: x == y
          - name: using when condition
            debug:
                    msg: "x is present in my_list"
            when: x in my_list



                    

