---
- hosts: two
  become: true
  become_user: root
  gather_facts: false
  tasks:
          - name: uncommenting a line
            lineinfile:
                    path: /home/ansible/httpd.conf
                    regexp: '(^# Listen .*)'
                    line: 'Listen 80'

