---
- hosts: two
  become: true
  become_user: root
  tasks:
          - name: Displaying inventory hostname
            debug:
                    var: inventory_hostname
          - name: Displaying hostvars
            debug:
                    var: hostvars[inventory_hostname]
