---
- hosts: all
  become: true
  become_user: root
  gather_facts: false
  tasks:
          - name: working on debug module
            debug:
                    var: inventory_hostname
                    #                    msg: "The hostname is: {{ inventory_hostname }}"


